
CREATE DATABASE :APP_DATABASE_NAME
WITH OWNER = postgres
        ENCODING = 'UTF8'
        TABLESPACE = pg_default
        LC_COLLATE = :LC_NAME
        LC_CTYPE = :LC_NAME
        CONNECTION LIMIT = -1;

ALTER DATABASE :APP_DATABASE_NAME
    SET client_encoding ='UTF8';

CREATE ROLE :APP_USER_NAME LOGIN
    ENCRYPTED PASSWORD :APP_USER_NAME
    NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE;

CREATE ROLE :APP_WWW_USER_NAME LOGIN
    ENCRYPTED PASSWORD :APP_WWW_USER_NAME
    NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE;

CREATE TABLESPACE :APP_DATABASE_NAME
OWNER :APP_USER_NAME
LOCATION 'APP_TABLESPACES';

ALTER ROLE :APP_USER_NAME SET default_tablespace TO :APP_DATABASE_NAME;

ALTER DATABASE :APP_DATABASE_NAME OWNER to :APP_USER_NAME;
