
CREATE DATABASE :APP_DATABASE_NAME
WITH OWNER = postgres
        ENCODING = 'UTF8'
        TABLESPACE = pg_default
        LC_COLLATE = :LC_NAME_QUOTED
        LC_CTYPE = :LC_NAME_QUOTED
        CONNECTION LIMIT = -1;

ALTER DATABASE :APP_DATABASE_NAME
    SET client_encoding ='UTF8';

CREATE ROLE :APP_USER_NAME LOGIN
    ENCRYPTED PASSWORD :APP_USER_NAME_QUOTED
    NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE;

CREATE ROLE :APP_WWW_USER_NAME LOGIN
    ENCRYPTED PASSWORD :APP_WWW_USER_NAME_QUOTED
    NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE;

CREATE TABLESPACE :APP_DATABASE_NAME
    owner :APP_USER_NAME
    LOCATION :APP_TABLESPACES_QUOTED;

ALTER ROLE :APP_USER_NAME
    set default_tablespace= :APP_DATABASE_NAME;

ALTER DATABASE :APP_DATABASE_NAME OWNER to :APP_USER_NAME;
